### ISSUE TITLE
npi CLI

### ISSUE THREAD

**Issue by amowu** [kidark/wtd#2]
- [x] Install CLI by `$ npm install wtd -g`
- [x] List dependencies description by `$ wtd <manager> <name>[@<version>]`, ex: `$ wtd npm express`
- [ ] List dependencies URL by `-u` or `--list-url`
- [ ] List devDenpedencies by `-d` or `--list-dev`
- [ ] Parse by repo URL, ex: `$ wtd https://github.com/expressjs/express`

**Comment by hanksudo** [comment]
@amowu There is a exists package called `npi`, we need a new name.

I would like to have a option to append package url on result, what do you think?

**Comment by amowu** [comment]
@hanksudo How about `-u` or `--list-url`?

**Comment by amowu** [comment]
@hanksudo How about **npm-info** as new name, inspired by [npm-check](https://github.com/dylang/npm-check)

**Comment by hanksudo** [comment]
@amowu `npm-info` already exists.

`npm info npm-info`

Maybe `npm-pkg-info`, `npm-hound` or something like that ? XD

**Comment by amowu** [comment]
`npm-wtf` 😏

**Comment by hanksudo** [comment]
@amowu how about `npm-wtp`

What the packages

**Comment by amowu** [comment]
Move todo to #4
